/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPriceCalculator } from "../IPriceCalculator";

export class IPriceCalculator__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceCalculator {
    return new Contract(address, _abi, signerOrProvider) as IPriceCalculator;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "assets",
        type: "address[]",
      },
    ],
    name: "pricesInUSD",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "valueOfAsset",
    outputs: [
      {
        internalType: "uint256",
        name: "valueInBNB",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "valueInUSD",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
